### ISSUE TITLE
Add better support for diacritics in text

### ISSUE THREAD

**Issue by chrisladd** [chrisladd/lunchbot#8]
[Current solution](https://github.com/chrisladd/lunchbot/blob/master/renderer.rb#L70) for crashy unicode is:

`arg.encode("utf-8", "binary", :undef => :replace)`

Which fixes this crash:

```
2016-03-24T15:31:25.839542+00:00 heroku[router]: at=info method=POST path="/slash" host=nytlunchbot.herokuapp.com request_id=90f33660-299f-45d7-90f7-de203ba415db fwd="52.90.38.136" dyno=web.1 connect=2ms service=540ms status=500 bytes=326
2016-03-24T15:31:25.830813+00:00 app[web.1]:    /app/app.rb:70:in `encode'
2016-03-24T15:31:25.830801+00:00 app[web.1]: 2016-03-24 11:31:25 - Encoding::UndefinedConversionError - "\xFC" from ASCII-8BIT to UTF-8:
2016-03-24T15:31:25.830814+00:00 app[web.1]:    /app/app.rb:70:in `to_json'
2016-03-24T15:31:25.830815+00:00 app[web.1]:    /app/app.rb:70:in `send_msg_obj'
```

But produces output like this:
 D�sseldorf Mustard

Instead of:
Düsseldorf Mustard

**Comment by chrisladd** [comment]
Some strategies:
http://stackoverflow.com/questions/13003287/encodingundefinedconversionerror
